// src/world/themes.ts
import { LayerConfig } from "./generators";

export const WorldThemes: { [key: string]: LayerConfig[] } = {
  desert_start: [
    {
      type: "stars_far",
      speed: 0.01,
      count: 150,
      generator: "generateStar",
      options: { colors: ["#FFFFFF", "#FFFFE0"], sizes: [1, 1] },
    },
    {
      type: "stars_near",
      speed: 0.02,
      count: 70,
      generator: "generateStar",
      options: { colors: ["#FFFFFF", "#F0F8FF"], sizes: [1, 2] },
    },
    {
      type: "celestial",
      speed: 0.03,
      count: 1,
      generator: "generateCelestialBody",
      options: { type: "sun" },
    },
    {
      type: "distant_mountains",
      speed: 0.08,
      count: 10,
      generator: "generateDesertDistant",
      options: {
        heightRange: [80, 150],
      },
    },
    {
      type: "mid_mesas",
      speed: 0.25,
      count: 15,
      generator: "generateDesertMid",
      options: { type: "mesa" },
    },
    {
      type: "near_rocks_cactus",
      speed: 0.5,
      count: 20,
      generator: "generateDesertMid",
      options: { type: "mixed" },
    },
    {
      type: "ground_texture",
      speed: 1.0,
      count: 8,
      generator: "generateDesertGround",
    },
    {
      type: "foreground_debris",
      speed: 1.5,
      count: 30,
      generator: "generateForegroundDebris",
      options: { types: ["rock", "tumbleweed_small"] },
    },
  ],
  gaming: [
    {
      type: "stars_far",
      speed: 0.02,
      count: 100,
      generator: "generateStar",
      options: { colors: ["#FF00FF", "#00FFFF"], sizes: [1, 1] },
    },
    {
      type: "celestial",
      speed: 0.04,
      count: 1,
      generator: "generateCelestialBody",
      options: { type: "glitch_moon" },
    },
    {
      type: "pixel_clouds",
      speed: 0.1,
      count: 15,
      generator: "generatePixelCloud",
      options: {
        sizeRange: [30, 80],
      },
    },
    {
      type: "distant_structures",
      speed: 0.25,
      count: 12,
      generator: "generateGamingDistant",
    },
    {
      type: "mid_elements",
      speed: 0.6,
      count: 25,
      generator: "generateGamingMid",
    },
    {
      type: "ground_texture",
      speed: 1.0,
      count: 8,
      generator: "generateGamingGround",
    },
    {
      type: "foreground_debris",
      speed: 1.5,
      count: 25,
      generator: "generateForegroundDebris",
      options: { types: ["glitch_cube", "wire", "pixel_coin"] },
    },
  ],
  futuristic: [
    {
      type: "stars_far",
      speed: 0.01,
      count: 200,
      generator: "generateStar",
      options: { colors: ["#A0A0FF", "#C0C0FF"], sizes: [1, 1] },
    },
    {
      type: "stars_near",
      speed: 0.02,
      count: 100,
      generator: "generateStar",
      options: { colors: ["#FFFFFF", "#E0E0FF"], sizes: [1, 2] },
    },
    {
      type: "nebulae_distant",
      speed: 0.03,
      count: 5,
      generator: "generateNebula",
    },
    {
      type: "celestial",
      speed: 0.04,
      count: 1,
      generator: "generateCelestialBody",
      options: { type: "tech_moon" },
    },
    {
      type: "sky_traffic",
      speed: 0.15,
      count: 20,
      generator: "generateFuturisticSkyElement",
    },
    {
      type: "distant_towers",
      speed: 0.3,
      count: 15,
      generator: "generateFuturisticDistant",
    },
    {
      type: "mid_platforms",
      speed: 0.55,
      count: 20,
      generator: "generateFuturisticMid",
    },
    {
      type: "ground_guideways",
      speed: 1.0,
      count: 8,
      generator: "generateFuturisticGround",
    },
    {
      type: "foreground_debris",
      speed: 1.5,
      count: 20,
      generator: "generateForegroundDebris",
      options: { types: ["metal_shard", "glowing_bit", "circuit_piece"] },
    },
  ],
  industrial: [
    {
      type: "dense_clouds_low",
      speed: 0.08,
      count: 10,
      generator: "generatePixelCloud",
      options: {
        sizeRange: [80, 150],
        yPosRange: [0.3, 0.6],
      },
    },
    {
      type: "dense_clouds_high",
      speed: 0.12,
      count: 12,
      generator: "generatePixelCloud",
      options: {
        sizeRange: [60, 120],
        yPosRange: [0.1, 0.4],
      },
    },
    {
      type: "distant_smokestacks",
      speed: 0.25,
      count: 12,
      generator: "generateIndustrialDistant",
      options: { type: "smokestack" },
    },
    {
      type: "mid_buildings_pipes",
      speed: 0.6,
      count: 20,
      generator: "generateIndustrialMid",
    },
    {
      type: "ground_asphalt_cracks",
      speed: 1.0,
      count: 8,
      generator: "generateIndustrialGround",
    },
    {
      type: "foreground_debris",
      speed: 1.5,
      count: 35,
      generator: "generateForegroundDebris",
      options: { types: ["rubble", "rusty_pipe_fragment", "gear"] },
    },
  ],
};
